
def collatz_sequence(num):
    seq = []

    while num > 1:
        seq.append(num)
        if num % 2 == 0:
            num /= 2
        else:
            num = (num * 3) + 1

    seq.append(1)

    return seq


def find_longest_seq():
    longest_seq = 0
    number = 0

    for x in range(1000000, 1, -1):
        seq_len = len(collatz_sequence(x))
        if seq_len > longest_seq:
            number = x
            longest_seq = seq_len

    print("Longest sequence is {} generated by starting at {}".format(longest_seq, number))

find_longest_seq()